<template>
  <div class="flex h-dvh flex-col divide-y-[1px] bg-slate-100">
    <AppNavBar />

    <div
      class="responsive-height flex w-full flex-col gap-4 overflow-auto py-5"
    >
      <!-- TITLE -->
      <div class="container mx-auto mt-3">
        <h1 class="text-xl font-semibold">Demo Checkout Page</h1>
        <p class="text-sm">
          This is a dummy checkout page using NORBr's
          <a
            href="https://developer.norbr.io/#hosted-elements"
            target="_blank"
            class="underline"
          >
            Hosted Elements integration
          </a>

          for payments.
        </p>
      </div>

      <!-- CONTENT -->
      <div class="container mx-auto flex gap-4">
        <!-- left: payment goes here -->
        <div class="w-2/3 rounded border border-gray-200 bg-white p-6">
          <AppNotification>
            *The payment form below is intentionally unstyled to show the
            default look.
          </AppNotification>

          <div id="norbr-payment-container"></div>

          <div class="mt-4 flex flex-col gap-1" v-if="isAwaitingServer">
            <div class="h-4 animate-pulse rounded-lg bg-gray-300"></div>
            <div class="h-4 animate-pulse rounded-lg bg-gray-300"></div>
            <div class="h-4 animate-pulse rounded-lg bg-gray-300"></div>
          </div>

          <!-- response data here... -->
          <div class="flex w-full flex-col gap-4" v-if="trxResult">
            <div class="flex flex-col gap-1">
              <h1 class="font-semibold">Response Data</h1>
              <textarea
                class="h-96 w-full rounded bg-gray-100 p-4 font-mono"
                v-model="trxResult"
                readonly
              >
              </textarea>
            </div>

            <div>
              <button
                class="rounded bg-amber-300 px-4 py-1 hover:bg-amber-400"
                @click="reloadPage"
              >
                Reload Page
              </button>
            </div>
          </div>
        </div>

        <!-- right: some checkout data here -->
        <div
          class="flex w-1/3 flex-col gap-4 rounded border border-gray-200 bg-white p-6"
        >
          <AppNotification>
            *The Checkout will be generated by the server using the information
            below.
          </AppNotification>

          <AppCustomerDetails />
          <AppShippingDetails />
          <AppPurchaseDetails />
        </div>
      </div>
    </div>

    <footer class="h-5 bg-white"></footer>
  </div>
</template>

<script lang="ts" setup>
  import axios from 'axios'

  const appName = useState('appName', () => 'NORBr | Test Integration')

  useHead({
    title: appName,
  })

  const isAwaitingServer = ref(false)
  const trxResult = ref('')

  /**
   * customer information
   */
  const customerEmail = useState('customerEmail', () => 'bo@payreto.com')
  const customerFirstName = useState('customerFirstName', () => 'John')
  const customerLastName = useState('customerLastName', () => 'Wick')
  const customerStreetName = useState(
    'customerStreetName',
    () => 'Unit A&D, 122 Valero Street, Bel-air'
  )
  const customerAddressCity = useState('customerAddressCity', () => 'Makati')
  const customerAddressZipCode = useState(
    'customerAddressZipCode',
    () => '1227'
  )
  const customerAddressCountry = useState('customerAddressCountry', () => 'PH')

  /**
   * shipping information
   */
  const shippingAddressStreetNameLine1 = useState(
    'shippingAddressStreetNameLine1',
    () => 'Unit A&D, 122 Valero Street, Bel-air'
  )
  const shippingAddressCity = useState('shippingAddressCity', () => 'Makati')
  const shippingAddressZipCode = useState(
    'shippingAddressZipCode',
    () => '1227'
  )
  const shippingAddressCountry = useState('shippingAddressCountry', () => 'PH')

  const reloadPage = () => {
    location.reload()
  }

  //
  onMounted(() => {
    const configuration = {
      publicapikey: import.meta.env.VITE_NORBR_PUBLIC_KEY,
      locale: 'en',
      environment: 'sandbox',
      tokentype: 'oneshot',
      paymentmethods: JSON.stringify(myPaymentMethods),
      displayButtons: true,
      displayCardHolder: true,
      displaySave: false,
      onSubmit: async () => {
        // send token to server for checkout and order processing
        try {
          isAwaitingServer.value = true
          const res = await axios.post('/api/submitPayment', {
            token: norbr.token,
            paymentMethodName: norbr.paymentMethodName,
            customerEmail: customerEmail.value,
            customerFirstName: customerFirstName.value,
            customerLastName: customerLastName.value,
            customerStreetName: customerStreetName.value,
            customerAddressCity: customerAddressCity.value,
            customerAddressZipCode: customerAddressZipCode.value,
            customerAddressCountry: customerAddressCountry.value,

            shippingAddressStreetNameLine1:
              shippingAddressStreetNameLine1.value,
            shippingAddressCity: shippingAddressCity.value,
            shippingAddressZipCode: shippingAddressZipCode.value,
            shippingAddressCountry: shippingAddressCountry.value,
          })

          trxResult.value = JSON.stringify(res.data, undefined, 4)

          //
        } catch (error) {
          trxResult.value = JSON.stringify(
            {
              msg: 'Server error, check browser console for details.',
            },
            undefined,
            4
          )

          console.error(error)

          //
        } finally {
          isAwaitingServer.value = false
        }
      },
    }

    // @ts-ignore
    const norbr = new Norbr(configuration)
  })
</script>

<style>
  .responsive-height {
    height: calc(100dvh - 56px);
  }
</style>
