<template>
  <div class="flex h-dvh flex-col divide-y-[1px] bg-slate-100">
    <AppNavBar />

    <div
      class="responsive-height flex w-full flex-col gap-4 overflow-auto py-5"
    >
      <!-- TITLE -->
      <div class="container mx-auto">
        <h1 class="text-xl font-semibold">Demo Checkout Page</h1>
        <p class="text-sm">
          This is a dummy checkout page using NORBr's
          <AppExternalLink
            link="https://developer.norbr.io/#hosted-elements"
            text="Hosted Elements integration"
          />
          for payments.
        </p>
      </div>

      <!-- CONTENT -->
      <div class="container mx-auto flex gap-2">
        <!-- left: payment goes here -->
        <div
          class="flex w-2/3 flex-col gap-4 rounded border border-gray-200 bg-white p-6"
        >
          <AppNotification>
            <p>
              The payment form below (highlighted in pink) is intentionally left
              (mostly) unstyled to show the default look it comes with, but it
              is recommended for the merchant to style the forms to match their
              shop's theme. Some of the form inputs in this demo may have been
              reset by
              <AppExternalLink
                link="https://tailwindcss.com/docs/plugins#forms"
                text="Tailwind Forms"
              />.
            </p>
          </AppNotification>

          <!-- NORBr conatiner class -->
          <div
            id="norbr-payment-container"
            class="bg-pink-100"
            v-if="displayGwDiv"
          ></div>

          <!-- display skeleton loader and response data here -->
          <Transition mode="out-in">
            <AppSkeletonLoader v-if="isAwaitingServer" />
            <div
              class="flex w-full flex-col gap-4"
              v-else-if="trxResult && !isAwaitingServer"
            >
              <div class="flex flex-col gap-1">
                <h1 class="text-xl font-semibold">
                  Response Data
                  <span class="text-sm font-normal text-black/50">JSON</span>
                </h1>

                <textarea
                  class="h-96 w-full rounded border-none bg-gray-100 p-4 font-mono text-sm transition focus:ring focus:ring-blue-300 focus:ring-opacity-50"
                  v-model="trxResult"
                  readonly
                >
                </textarea>
              </div>

              <div>
                <button
                  class="rounded bg-amber-300 px-4 py-2 text-amber-900 transition hover:bg-amber-400"
                  @click="reloadPage"
                >
                  Reload Payment Form
                </button>
              </div>
            </div>
          </Transition>
        </div>

        <!-- right: some checkout data here -->
        <div
          class="flex w-1/3 flex-col gap-4 rounded border border-gray-200 bg-white p-6"
        >
          <AppNotification>
            Checkout data will be generated by the server using the information
            below. The
            <kbd class="font-semibold">order_merchant_id</kbd>
            will also be server generated.
          </AppNotification>

          <AppCustomerDetails />
          <AppShippingDetails />
          <AppPurchaseDetails />
        </div>
      </div>
    </div>

    <footer class="h-5 bg-white"></footer>
  </div>
</template>

<script lang="ts" setup>
  import axios from 'axios'

  const appName = useState('appName', () => 'NORBr | Test Integration')

  useHead({
    title: appName,
  })

  const displayGwDiv = ref(true)
  const isAwaitingServer = ref(false)
  const trxResult = ref('')

  /**
   * customer information
   */
  const customerEmail = useState('customerEmail', () => 'bo@payreto.com')
  const customerFirstName = useState('customerFirstName', () => 'John')
  const customerLastName = useState('customerLastName', () => 'Wick')
  const customerStreetName = useState(
    'customerStreetName',
    () => 'Unit A&D, 122 Valero Street, Bel-air'
  )
  const customerAddressCity = useState('customerAddressCity', () => 'Makati')
  const customerAddressZipCode = useState(
    'customerAddressZipCode',
    () => '1227'
  )
  const customerAddressCountry = useState('customerAddressCountry', () => 'PH')

  /**
   * shipping information
   */
  const shippingAddressStreetNameLine1 = useState(
    'shippingAddressStreetNameLine1',
    () => 'Unit A&D, 122 Valero Street, Bel-air'
  )
  const shippingAddressCity = useState('shippingAddressCity', () => 'Makati')
  const shippingAddressZipCode = useState(
    'shippingAddressZipCode',
    () => '1227'
  )
  const shippingAddressCountry = useState('shippingAddressCountry', () => 'PH')

  const reloadPage = () => {
    location.reload()
  }

  /**
   * purchase info
   */
  const trxTotalAmount = useState('trxTotalAmount', () => 10.0)

  //
  onMounted(() => {
    const configuration = {
      publicapikey: import.meta.env.VITE_NORBR_PUBLIC_KEY,
      locale: 'en',
      environment: 'sandbox',
      tokentype: 'oneshot',
      paymentmethods: JSON.stringify(myPaymentMethods),
      displayButtons: true,
      displayCardHolder: true,
      displaySave: false,
      onSubmit: async () => {
        displayGwDiv.value = false

        // send token to server for checkout and order processing
        try {
          isAwaitingServer.value = true
          const res = await axios.post('/api/submitPayment', {
            token: norbr.token,
            paymentMethodName: norbr.paymentMethodName,
            customerEmail: customerEmail.value,
            customerFirstName: customerFirstName.value,
            customerLastName: customerLastName.value,
            customerStreetName: customerStreetName.value,
            customerAddressCity: customerAddressCity.value,
            customerAddressZipCode: customerAddressZipCode.value,
            customerAddressCountry: customerAddressCountry.value,

            shippingAddressStreetNameLine1:
              shippingAddressStreetNameLine1.value,
            shippingAddressCity: shippingAddressCity.value,
            shippingAddressZipCode: shippingAddressZipCode.value,
            shippingAddressCountry: shippingAddressCountry.value,

            trxTotalAmount: trxTotalAmount.value,
          })

          trxResult.value = JSON.stringify(res.data, undefined, 4)

          //
        } catch (error) {
          trxResult.value = JSON.stringify(
            {
              msg: 'Server error, check browser console for details.',
            },
            undefined,
            4
          )

          console.error(error)

          //
        } finally {
          isAwaitingServer.value = false
        }
      },
    }

    // @ts-ignore
    const norbr = new Norbr(configuration)
  })
</script>

<style>
  .responsive-height {
    height: calc(100dvh - 56px);
  }

  .v-enter-active,
  .v-leave-active {
    transition: opacity 0.3s ease;
  }

  .v-enter-from,
  .v-leave-to {
    opacity: 0;
  }
</style>
